sudo: required
services:
  - docker

script:
  - echo "Build local image"
  - docker build -t gitlab .
  - docker images
  - echo "Run local image"
  - sudo ulimit -c 0
  - sudo ulimit -d unlimited
  - sudo ulimit -e 0
  - sudo ulimit -f unlimited
  - sudo ulimit -i 62793
  - sudo ulimit -l 64
  - sudo ulimit -m unlimited
    # WARNING: Increasing the global file descriptor limit increases RAM
    # consumption on startup dramatically!
  - sudo ulimit -n 50000
  - sudo ulimit -q 819200
  - sudo ulimit -r 0
  - sudo ulimit -s 10240
  - sudo ulimit -t unlimited
  - sudo ulimit -u unlimited
  - sudo ulimit -v unlimited
  - sudo ulimit -x unlimited  
  - docker run --name my-gitlab -d -p 9090:80 gitlab
  - echo "Wait gitlab to start up"    
  - sleep 30
  - docker ps -a  
  - docker logs my-gitlab
  - docker exec -it my-gitlab ps -ef
  - echo "Checking gitlab"
  - curl http://localhost:9090/
  - docker stop my-gitlab
  - echo "Testing public image on Docker Hub"
  - docker run -d -p 9090:80  --name nguoianphu-gitlab nguoianphu/docker-gitlab
  - docker ps -a
  - docker images  
  - sleep 30  
  - docker logs nguoianphu-gitlab
  - docker exec -it nguoianphu-gitlab ps -ef
  - echo "Checking gitlab"
  - curl http://localhost:9090
  - docker stop nguoianphu-gitlab
