sudo: required
services:
  - docker

script:
  - echo "Build local image"
  - docker build -t gitlab .
  - docker images
  - echo "Run local image"
  - sudo sh -c "ulimit -c 0"
  - sudo sh -c "ulimit -d unlimited"
  # - sudo sh -c "ulimit -e 0"
  - sudo sh -c "ulimit -f unlimited"
  # - sudo sh -c "ulimit -i 62793"
  - sudo sh -c "ulimit -l 64"
  - sudo sh -c "ulimit -m unlimited"
    # WARNING: Increasing the global file descriptor limit increases RAM
    # consumption on startup dramatically!
  - sudo sh -c "ulimit -n 50000"
  # - sudo sh -c "ulimit -q 819200"
  # - sudo sh -c "ulimit -r 0"
  - sudo sh -c "ulimit -s 10240"
  - sudo sh -c "ulimit -t unlimited"
  # - sudo sh -c "ulimit -u unlimited"
  - sudo sh -c "ulimit -v unlimited"
  # - sudo sh -c "ulimit -x unlimited"
  - sudo sysctl -w vm.overcommit_memory=1
  # - docker run --name my-gitlab -d -p 9090:80 gitlab
  - sudo docker run --detach \
    --hostname localhost \
    --publish 443:443 --publish 80:80 --publish 22:22 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    gitlab
  - echo "Wait gitlab to start up"    
  - sleep 30
  - docker ps -a  
  - docker logs my-gitlab
  - docker exec -it my-gitlab ps -ef
  - echo "Checking gitlab"
  - docker exec -it my-gitlab netstat -anlp
  - curl http://localhost/
  - docker stop my-gitlab
  - echo "Testing public image on Docker Hub"
  - docker run -d -p 9090:80  --name nguoianphu-gitlab nguoianphu/docker-gitlab
  - docker ps -a
  - docker images  
  - sleep 30  
  - docker logs nguoianphu-gitlab
  - docker exec -it nguoianphu-gitlab ps -ef
  - echo "Checking gitlab"
  - curl http://localhost:9090
  - docker stop nguoianphu-gitlab
